apply plugin: 'c'

model {
    components {
        hostTestDriver(NativeExecutableSpec) {
            targetPlatform "tinkerLocal"
	    sources {
	        c {
                    exportedHeaders {
                        srcDirs "src/hostTestDriver/headers"
                    }
	            lib project: ':base', library: 'base', linkage: 'static'
	            lib project: ':kernel', library: 'kernelTests', linkage: 'static'
                    lib project: ':kernel', library: 'kernel', linkage: 'static'
                    lib project: ':api', library: 'api', linkage: 'static'
                }
	    }
        }
    }
}
