include 'base'
include 'api'
include 'kernel'
include 'archArm'
include 'driverSocBcm2835'
include 'bspRaspberryPi'
include 'hostTestDriver'
include 'libelf'
include 'elfLoaderTest'
include 'elfNewlibTest'
include 'utilBinToH'
include 'binutils'
include 'gcc'
include 'newlib'
include 'gdb'
