apply plugin: 'assembler'
apply plugin: 'c'

task downloadNewlib(type: Downloader) {
    sourceUrl = 'ftp://sourceware.org/pub/newlib/newlib-2.5.0.tar.gz'
    target = file('newlib-2.5.0.tar.gz')
}

task untarNewlib (type: Copy) {
    from tarTree(resources.gzip('newlib-2.5.0.tar.gz'))
    into getProjectDir().getAbsolutePath()  + "//src"
}

untarNewlib.dependsOn downloadNewlib

/* -------------------------------- arm-eabi --------------------------- */

task setupNewlibArm (type: BuildSetup) {
    root = getProjectDir().getAbsolutePath()
    target = 'arm-eabi'
}

setupNewlibArm.dependsOn untarNewlib

task configureNewlibArm (type:Exec) {
  workingDir getProjectDir().getAbsolutePath() + "//build-arm-eabi"
  commandLine 'bash',
    '-c',
    'rm -rf *;\
    rm -rf ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    mkdir -p ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    cp -R ../src/newlib/newlib ../src/newlib-2.5.0;\
    cp ../../api/src/api/headers/* ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    cp ../../api/src/api/c/* ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    cp ../../base/src/base/headers/tgt_types.h ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    cp ../../archArm/src/archArm/headers/tgt_mem.h ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    cp ../../archArm/src/archArm/headers/arm5/tgt_io.h ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    CFLAGS_FOR_TARGET=\'-Wno-implicit-int -Wno-implicit-function-declaration -w -Os\' ../src/newlib-2.5.0/configure --prefix=' + getProjectDir().getAbsolutePath().replace("\\","/") + '/../arm-eabi --target=arm-eabi --disable-multilib --disable-newlib-atexit-dynamic-alloc --disable-werror'
}

configureNewlibArm.dependsOn setupNewlibArm

task makeNewlibArm (type:Exec) {
    workingDir getProjectDir().getAbsolutePath() + "//build-arm-eabi"
    commandLine 'bash',
        '-c',
        'CFLAGS_FOR_TARGET=\'-Wno-implicit-int -Wno-implicit-function-declaration -w -Os\' ' + project.getProperties().get("MAKE") + ' -' + project.getProperties().get("CONBUILDS")
}

makeNewlibArm.dependsOn configureNewlibArm

task makeInstallNewlibArm (type:Exec) {
    workingDir getProjectDir().getAbsolutePath() + "//build-arm-eabi"
    commandLine 'bash',
        '-c',
        'make install'
}

makeInstallNewlibArm.dependsOn makeNewlibArm

/* -------------------------------- aarch64-elf --------------------------- */

task setupNewlibAArch64 (type: BuildSetup) {
    root = getProjectDir().getAbsolutePath()
    target = 'aarch64-elf'
}

setupNewlibAArch64.dependsOn untarNewlib

task configureNewlibAArch64 (type:Exec) {
  workingDir getProjectDir().getAbsolutePath() + "//build-aarch64-elf"
  commandLine 'bash',
    '-c',
    'rm -rf *;\
    rm -rf ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    mkdir -p ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    cp -R ../src/newlib/newlib ../src/newlib-2.5.0;\
    cp ../../api/src/api/headers/* ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    cp ../../api/src/api/c/* ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    cp ../../base/src/base/headers/tgt_types.h ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    cp ../../archArm/src/archArm/headers/tgt_mem.h ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    cp ../../archArm/src/archArm/headers/arm5/tgt_io.h ../src/newlib-2.5.0/newlib/libc/sys/arm/;\
    CFLAGS_FOR_TARGET=\'-Wno-implicit-int -Wno-implicit-function-declaration -w -Os\' ../src/newlib-2.5.0/configure --prefix=' + getProjectDir().getAbsolutePath().replace("\\","/") + '/../aarch64-elf --target=aarch64-elf --disable-multilib --disable-newlib-atexit-dynamic-alloc --disable-werror'
}

configureNewlibAArch64.dependsOn setupNewlibAArch64

task makeNewlibAArch64 (type:Exec) {
    workingDir getProjectDir().getAbsolutePath() + "//build-aarch64-elf"
    commandLine 'bash',
        '-c',
        'CFLAGS_FOR_TARGET=\'-Wno-implicit-int -Wno-implicit-function-declaration -w -Os\' ' + project.getProperties().get("MAKE") + ' -' + project.getProperties().get("CONBUILDS")
}

makeNewlibAArch64.dependsOn configureNewlibAArch64

task makeInstallNewlibAArch64 (type:Exec) {
    workingDir getProjectDir().getAbsolutePath() + "//build-aarch64-elf"
    commandLine 'bash',
        '-c',
        'make install'
}

makeInstallNewlibAArch64.dependsOn makeNewlibAArch64

/* -------------------------------- clean --------------------------- */

task cleanNewLib(type:Exec) {
	commandLine 'bash',
		'-c',
		'rm -rf build-arm-eabi;\
		 rm -rf src//newlib-*;\
         rm -rf *.tar.gz'
}

cleanNewLib.outputs.upToDateWhen {false}
clean.finalizedBy(cleanNewLib)

class Downloader extends DefaultTask {
    @Input
    String sourceUrl

    @OutputFile
    File target

    @TaskAction
    void download() {
        ant.get(src: sourceUrl, dest: target)
    }
}

class BuildSetup extends DefaultTask {
    @Input
    String root
    @Input
    String target

    @TaskAction
    void setup() {
        java.io.File path = new File(root + "//build-" + target)
        path.mkdirs();
    }
}
