apply plugin: 'c'

model {
	components {
	    kernel(NativeLibrarySpec) {
	        targetPlatform "tinkerArm4Soft"
	        targetPlatform "tinkerArm7HardVfp"
                targetPlatform "tinkerArm8aHardVfp"
	        targetPlatform "tinkerLocal"
	        sources {
		    c {
		        lib project: ':base', library: 'base', linkage: 'static'
		        lib project: ':libelf', library: 'libelf', linkage: 'static'
		    }
	        }
                binaries.withType(SharedLibraryBinarySpec) {
                    buildable = false
                }
	    }
	    kernelTests(NativeLibrarySpec) {
	        targetPlatform "tinkerArm4Soft"
	        targetPlatform "tinkerArm7HardVfp"
                targetPlatform "tinkerArm8aHardVfp"
	        targetPlatform "tinkerLocal"
	        sources {
                    c {
		        lib project: ':base', library: 'base', linkage: 'static'
		        lib project: ':kernel', library: 'kernel', linkage: 'static'
		    }
	        }
                binaries.withType(SharedLibraryBinarySpec) {
                    buildable = false
                }
	    }
	}
}
