/*
 *
 * SOS Source Code
 * __________________
 *
 *  [2009] - [2013] Samuel Steven Truscott
 *  All Rights Reserved.
 */
#ifndef SOS_API_ERRORS_H_
#define SOS_API_ERRORS_H_

typedef enum error_enum
{
	UNKNOWN_ERROR = 0,
	NO_ERROR,
	OUT_OF_MEMORY,
	SIZE_TOO_SMALL,

	MEM_NOT_ALIGNED,

	PARAMETERS_NULL,
	PARAMETERS_INVALID,
	PARAMETERS_OUT_OF_RANGE,

	INVALID_CONTEXT,
	OBJECT_TABLE_FULL,
	INVALID_OBJECT,
	WRONG_OBJ_TYPE,
	OBJECT_ADD_FAILED,
	OBJECT_IN_INVALID_STATE,
	SEMAPHORE_EMPTY,
	ALARM_ID_UNKNOWN,

	DEVICE_ID_INVALID,
	DEVICE_USER_DATA_INVALID,
	DEVICE_REGISTER_INVALID,
	DEVICE_READ_BAD_ADDRESS,
	DEVICE_WRITE_BAD_ADDRESS,
	DEVICE_OPERATION_NOT_SUPPORTED,

	OBJECT_NAME_EXISTS_IN_REGISTRY,
	OBJECT_NOT_ADDED_TO_REGISTRY,
	OBJECT_NOT_IN_REGISTRY,
	OBJECT_NOT_RETRIEVED_FROM_REGISTRY,
	OBJECT_NOT_REMOVED_FROM_REGISTRY,

	UNEXPECTED_INTERRUPT,
	UNKNOWN_INTERRUPT_CAUSE,
	UNKNOWN_EXTERNAL_INTERRUPT_VECTOR,
	INTERRUPT_NO_EXT_VECTOR_SPECIFIED,
} error_t;

#endif /* SOS_API_ERRORS_H_ */
