/*
 *
 * TINKER Source Code
 * 
 *
 *  [2009] - [2013] Samuel Steven Truscott
 *  All Rights Reserved.
 */
#ifndef TINKER_API_ERRORS_H_
#define TINKER_API_ERRORS_H_

typedef enum error_enum
{
	UNKNOWN_ERROR = 0,
	NO_ERROR,
	OUT_OF_MEMORY,
	SIZE_TOO_SMALL,
	BLOCKED_RETRY,
	MEM_NOT_ALIGNED,
	PARAMETERS_NULL,
	PARAMETERS_INVALID,
	PARAMETERS_OUT_OF_RANGE,
	INVALID_CONTEXT,

	OBJECT_TABLE_FULL, // 10
	INVALID_OBJECT,
	WRONG_OBJ_TYPE,
	OBJECT_ADD_FAILED,
	OBJECT_IN_INVALID_STATE,
	SEMAPHORE_EMPTY,
	TIMER_CALLBACK_MISSING,
	SHM_WRONG_SIZE,
	ALARM_ID_UNKNOWN,
	UNKNOWN_PIPE,

	PIPE_FULL, // 20
	PIPE_POLARITY_WRONG,
	PIPE_RECEIVERS_FULL,
	PIPE_EMPTY,
	ALARM_ALREADY_CANCELLED,
	DEVICE_ID_INVALID,
	DEVICE_USER_DATA_INVALID,
	DEVICE_REGISTER_INVALID,
	DEVICE_READ_BAD_ADDRESS,

	DEVICE_WRITE_BAD_ADDRESS, // 30
	DEVICE_OPERATION_NOT_SUPPORTED,
	OBJECT_NAME_EXISTS_IN_REGISTRY,
	OBJECT_NOT_ADDED_TO_REGISTRY,
	OBJECT_NOT_IN_REGISTRY,
	OBJECT_NOT_RETRIEVED_FROM_REGISTRY,
	OBJECT_NOT_REMOVED_FROM_REGISTRY,
	NO_ROOT_INTERRUPT_HANDLER,
	UNEXPECTED_INTERRUPT,
	UNKNOWN_INTERRUPT_CAUSE,

	UNKNOWN_EXTERNAL_INTERRUPT_VECTOR, // 40
	INTERRUPT_NO_EXT_VECTOR_SPECIFIED,
	PIPE_MESSAGE_SIZE_NOT_ALIGNED,
	MMAP_NOT_ALLOWED_AT_ZERO

} error_t;

#endif /* TINKER_API_ERRORS_H_ */
